# Generated by Django 3.2.11 on 2023-03-12 10:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lululemon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logmessage',
            name='qrcode',
            field=models.CharField(default=django.utils.timezone.now, help_text='Enter 13-digit QR Code:', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logmessage',
            name='message',
            field=models.CharField(help_text='Enter username:', max_length=300),
        ),
    ]
