# Generated by Django 3.2.11 on 2023-03-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lululemon', '0002_auto_20230312_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='logmessage',
            name='product',
            field=models.TextField(default='lululemon Product', help_text='Enter Product:', max_length=300),
        ),
        migrations.AlterField(
            model_name='logmessage',
            name='qrcode',
            field=models.IntegerField(default='0000000000000', help_text='Enter 13-digit QR Code:', max_length=13),
        ),
    ]
