# Generated by Django 3.2.11 on 2023-03-14 10:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lululemon', '0003_auto_20230312_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmessage',
            name='log_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date logged'),
        ),
        migrations.AlterField(
            model_name='logmessage',
            name='message',
            field=models.CharField(help_text='Enter username:', max_length=100),
        ),
        migrations.AlterField(
            model_name='logmessage',
            name='product',
            field=models.TextField(default='product', help_text='Enter Product:', max_length=300),
        ),
        migrations.AlterField(
            model_name='logmessage',
            name='qrcode',
            field=models.IntegerField(default='0000000000000', help_text='Enter 13-digit QR Code:'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='default.jpg', upload_to='profile_images')),
                ('bio', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
