# Generated by Django 3.2.11 on 2023-03-14 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lululemon', '0004_auto_20230314_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logmessage',
            old_name='message',
            new_name='staffname',
        ),
    ]
