# Generated by Django 3.2.11 on 2023-03-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lululemon', '0005_rename_message_logmessage_staffname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmessage',
            name='qrcode',
            field=models.CharField(default='0000000000000', help_text='Enter 13-digit QR Code:', max_length=13),
        ),
        migrations.AlterField(
            model_name='logmessage',
            name='staffname',
            field=models.CharField(help_text='Enter username:', max_length=200),
        ),
    ]
