# Generated by Django 3.2.11 on 2023-04-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lululemon', '0007_auto_20230417_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_available',
        ),
        migrations.AddField(
            model_name='item',
            name='available_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
