# Generated by Django 3.2.11 on 2023-04-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lululemon', '0008_auto_20230419_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.RemoveField(
            model_name='item',
            name='name',
        ),
        migrations.AddField(
            model_name='checkout',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='barcode',
            field=models.CharField(default='0000000000000', help_text='Enter 13-digit QR Code:', max_length=13),
        ),
        migrations.AddField(
            model_name='item',
            name='checkin_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='checkout_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='product',
            field=models.TextField(default='product', help_text='Enter Product:', max_length=300),
        ),
        migrations.AddField(
            model_name='item',
            name='staffname',
            field=models.CharField(default='lululemon employee', help_text='Enter username:', max_length=200),
        ),
    ]
