# Generated by Django 4.0.3 on 2023-04-22 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lululemon', '0009_auto_20230419_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='barcode',
            field=models.CharField(default='0000000000000', max_length=13),
        ),
        migrations.AlterField(
            model_name='item',
            name='product',
            field=models.CharField(default='product', max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='staffname',
            field=models.CharField(default='lululemon employee', max_length=200),
        ),
    ]
