# Generated by Django 4.0.3 on 2023-04-22 06:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lululemon', '0010_alter_item_barcode_alter_item_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='barcode',
        ),
        migrations.AddField(
            model_name='item',
            name='color',
            field=models.CharField(default='Black', max_length=13),
        ),
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.CharField(default='S/M/L', max_length=13),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Generate unique ID', primary_key=True, serialize=False),
        ),
    ]
