# Generated by Django 4.0.3 on 2023-04-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lululemon', '0011_remove_item_barcode_item_color_item_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
