# Generated by Django 3.2.11 on 2023-04-22 08:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lululemon', '0012_alter_item_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(help_text='Type in the Category of the Item', max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='logmessage',
            name='qrcode',
        ),
        migrations.AddField(
            model_name='item',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='QR_CODE/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID to be generated', primary_key=True, serialize=False),
        ),
    ]
