# Generated by Django 3.2.11 on 2023-04-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lululemon', '0014_alter_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='categories',
            field=models.ManyToManyField(help_text='Select a category for this item', to='lululemon.Category'),
        ),
    ]
