# Generated by Django 3.2.11 on 2023-04-23 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lululemon', '0019_alter_category_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckOut',
        ),
    ]
